Buy:
    Preview:
        Menu: '&aBuying {item}'
        Lore:
        - ''
        - '&8&l➩ &7&nInfo:'
        - '&e&l➩ &7Purchase Price &8&l➥ &a&n{BuyPrice} &a$'
        - '&e&l➩ &7Sell Price &8&l➥ &c&n{SellPrice} &a$'
    More:
        Menu: '&aBuying stacks of {item}'
        Lore:
        - ''
        - '&8&l➩ &7&nInfo:'
        - ''
        - '&e&l➩ &7Purchase &e&n{stacks} stacks &7 of {item}'
        - '&e&l➩ &7Purchase Price &8&l➥ &e&n{price} &a$'
        - ''
        - '&8&l➩ &aClick to Purchase.'

Sell:
    Preview:
        Menu: '&cSelling {item}'
        Lore:
        - ''
        - '&8&l➩ &7&nInfo:'
        - '&e&l➩ &7Purchase Price &8&l➥ &a&n{BuyPrice} &a$'
        - '&e&l➩ &7Sell Price &8&l➥ &c&n{SellPrice} &a$'
    More:
        Menu: '&cSelling stacks of {item}'
        Lore:
        - ''
        - '&8&l➩ &7&nInfo:'
        - ''
        - '&e&l➩ &7Selling &e&n{stacks} stacks &7 of {item}'
        - '&e&l➩ &7Selling Price &8&l➥ &e&n{price} &a$'
        - ''
        - '&8&l➩ &aClick to Sell.'

Buttons:
    Confirm:
        Name: '&8» &aConfirm'
        Item: green glass block
        Slot: 39
    Cancel:
        Name: '&8» &cCancel'
        Item: red glass block
        Slot: 41
    Back:
        Name: '&8» &7&nBack'
        Item: nether star
    Buy-More:
        Name: '&8» &3&nBuy More'
        Item: chest
        Slot: 49
    Sell-More:
        Name: '&8» &c&nSell More'
        Item: chest
        Slot: 49
    Next-Page:
        Name: '&a&l» &7&nNext Page'
        Item: arrow
        Slot: 53
    Previous-Page:
        Name: '&c&l« &7&nPrevious Page'
        Item: arrow
        Slot: 45
    Add-1:
        Name: '&8» &aAdd 1'
        Item: green glass
        Slot: 24
    Add-10:
        Name: '&8» &aAdd 10'
        Item: green glass
        Slot: 25
    Remove-1:
        Name: '&8» &cRemove 1'
        Item: red glass
        Slot: 20
    Remove-10:
        Name: '&8» &cRemove 10'
        Item: red glass
        Slot: 21
    Set-1:
        Name: '&8» &cSet to 1'
        Item: red glass
        Slot: 19
    Set-64:
        Name: '&8» &aSet to 64'
        Item: green glass
        Slot: 26
    Close:
        Name: '&8⤓ &c&nClose&r &8⤓'
        Item: red dye
        Slot: 31

Messages:
    Purchase: '&8» &aYou bought &7&n{amount}&a of &7&n{item}&r &afor &7&n{price}.
        &a$'
    Sold: '&8» &cYou sold &7&n{amount}&c of &7&n{item} &cfor &7&n{price}. &a$'
    No-money: '&8» &aYou need &7&n{price} &a$ to buy &7&n{amount}&a of &7&n{item}'
    Inventory-Full: '&8» &aYou cannot hold this amount!'
    Not-Enough: '&8» &aYou do not have &7&n{amount}&a of &7&n{item} &ato sell.'
    No-Permission: '&8» &cYou do not have permission to use this Command!'
    Not-Sellable: '&cThis item cannot be sold.'

Sounds:
    Purchase:
        Sound: NOTE_STICKS
        Volume: 1.0
        Pitch: 1.0
    Sold:
        Sound: NOTE_STICKS
        Volume: 1.0
        Pitch: 1.0
    No-Money:
        Sound: ANVIL_BREAK
        Volume: 1.0
        Pitch: 1.0
    Not-Enough:
        Sound: ANVIL_BREAK
        Volume: 1.0
        Pitch: 1.0
    Open-Menu:
        Sound: CHICKEN_EGG_POP
        Volume: 1.0
        Pitch: 1.0
